[package]
name = "bevy_mod_picking"
version = "0.6.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A 3D mouse picking and raycasting plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "picking", "bevy", "raycast"]
categories = ["game-engines", "rendering"]
resolver = "2"


[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
  "render",
] }
# Local
bevy_picking_core = { path = "crates/bevy_picking_core" }
bevy_picking_input = { path = "crates/bevy_picking_input" }
bevy_picking_raycast = { optional = true, path = "crates/bevy_picking_raycast" }
bevy_picking_rapier = { optional = true, path = "crates/bevy_picking_rapier" }


[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
  "bevy_winit",
  "x11",
] }

[features]
default = ["raycast"]
raycast = ["bevy_picking_raycast"]
rapier = ["bevy_picking_rapier"]

[patch."https://github.com/bevyengine/bevy"]
bevy = { git = "https://github.com/aevyrie/bevy", branch = "viewport-rect-fix" }
