[package]
name = "bevy_mod_picking"
version = "0.6.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A 3D mouse picking and raycasting plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "picking", "bevy", "mod_raycast"]
categories = ["game-engines", "rendering"]
resolver = "2"

[workspace]
members = ["crates/*", "crates/backends/*"]
exclude = ["crates/backends"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
  "render",
] }
# Local
bevy_picking_core = { path = "crates/bevy_picking_core" }
bevy_picking_input = { path = "crates/bevy_picking_input" }
bevy_picking_selection = { optional = true, path = "crates/bevy_picking_selection" }
bevy_picking_highlight = { optional = true, path = "crates/bevy_picking_highlight" }
bevy_picking_raycast = { optional = true, path = "crates/backends/bevy_picking_raycast" }
bevy_picking_rapier = { optional = true, path = "crates/backends/bevy_picking_rapier" }
bevy_picking_shader = { optional = true, path = "crates/backends/bevy_picking_shader" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
  "bevy_winit",
  "x11",
  "bevy_gltf",
  "bevy_scene",
] }
bevy_mod_picking = { path = "", features = [
  "rapier",
  "pick_shader",
  "mod_raycast",
] }
bevy_rapier3d = "0.15"

[features]
default = ["mod_raycast", "highlight", "selection"]
highlight = ["bevy_picking_highlight"]
selection = ["bevy_picking_selection"]
mod_raycast = ["bevy_picking_raycast"]
rapier = ["bevy_picking_rapier"]
pick_shader = ["bevy_picking_shader"]


[patch.crates-io]
bevy_rapier3d = { path = "../bevy_rapier/bevy_rapier3d" }
nalgebra = { git = "https://github.com/dimforge/nalgebra", branch = "dev" }
parry2d = { git = "https://github.com/dimforge/parry", branch = "master" }
parry3d = { git = "https://github.com/dimforge/parry", branch = "master" }
rapier2d = { git = "https://github.com/dimforge/rapier", branch = "master" }
rapier3d = { git = "https://github.com/dimforge/rapier", branch = "master" }
